language: ruby

before_install:
  - gem install bundler
  - gem install rake

rvm: 2.7.0

services:
  - postgresql

before_script:
  - psql -U postgres -c 'CREATE DATABASE chitter_test;'

script:
  - bundle exec rake create_tables
  - bundle exec rspec
